services:
  bot:
    build: .
    image: spoopafu-bot:latest
    restart: unless-stopped
    depends_on:
      - ollama
    volumes:
      - ./cache:/usr/app/cache
    environment:
      SPOTIFY_USERNAME: ${SPOTIFY_USERNAME}
      SPOTIFY_PLAYLIST_ID: ${SPOTIFY_PLAYLIST_ID}
      SPOTIFY_REDIRECT_URI: ${SPOTIFY_REDIRECT_URI}
      SPOTIFY_CLIENT_ID: ${SPOTIFY_CLIENT_ID}
      SPOTIFY_CLIENT_SECRET: ${SPOTIFY_CLIENT_SECRET}
      DISCORD_TOKEN: ${DISCORD_TOKEN}
    networks:
      - spoopafu-bot

  ollama:
    image: docker.io/ollama/ollama:latest
    volumes:
      - ./ollama/ollama:/root/.ollama
    tty: true
    restart: unless-stopped
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
    networks:
      - spoopafu-bot

networks:
  spoopafu-bot:
    external: false
